global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'pptloc28@gmail.com'
  smtp_auth_username: 'pptloc28@gmail.com'
  smtp_auth_password: 'fowglnhmiameankm'
  resolve_timeout: 5m

route:
  receiver: 'team-email'
  routes:
    - match:
        severity: critical
      receiver: 'team-pagerduty'
    - match:
        severity: warning
      receiver: 'team-slack'

receivers:
  - name: 'team-email'
    email_configs:
      - to: 'pptloc28@gmail.com'
    webhook_configs:
      - url: 'https://discord.com/api/webhooks/1389518284637999114/EGkYVbjEuC0odPoTPCRZizzj2R-kzck96ZEdxYPzPduPddGjkAKx_joaIC8iLPO3u1wl'
        send_resolved: true

  - name: 'team-slack'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/placeholder'
        channel: '#alerts'

  - name: 'team-pagerduty'
    pagerduty_configs:
      - routing_key: 'placeholder-pagerduty-key'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

