name: CD - Deploy ASP.NET App

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Tag of Docker image to deploy'
        required: true
      environment:
        description: 'Target environment (e.g., production, staging)'
        required: true

env:
  DOCKER_REPO: pptloc/aspnetapp

jobs:
  deploy-to-vm:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}

    steps:
      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            IMAGE="${{ env.DOCKER_REPO }}:${{ inputs.image_tag }}"
            docker pull $IMAGE
            docker stop aspnetapp || true
            docker rm aspnetapp || true
            docker run -d --name aspnetapp -p 80:8080 $IMAGE
