
name: CD - Deploy to VM

on:
  push:
    tags:
      - '*'
    branches:
      - main

env:
  DOCKER_REPO: pptloc/aspnetapp

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract tag
        run: |
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull & Deploy on Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} <<EOF
            docker pull $DOCKER_REPO:$TAG
            docker stop aspnetapp || true && docker rm aspnetapp || true
            docker run -d --name aspnetapp -p 80:80 $DOCKER_REPO:$TAG
          EOF
