name: CI - Build and Test ASP.NET App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_IMAGE: pptloc/aspnetapp

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore aspnetapp.sln

      - name: Build
        run: dotnet build aspnetapp.sln --no-restore

      - name: Test
        run: dotnet test aspnetapp.sln --no-build

  docker-deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE .

      - name: Push Docker image
        run: docker push $DOCKER_IMAGE

      - name: SSH Deploy to Azure VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            docker pull $DOCKER_IMAGE
            docker stop aspnetapp || true
            docker rm aspnetapp || true
            docker run -d --name aspnetapp -p 80:80 $DOCKER_IMAGE
