name: CICD - ASP.NET App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_IMAGE: pptloc/aspnetapp

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore ./aspnet/aspnetapp/aspnetapp.sln

      - name: Build
        run: dotnet build ./aspnet/aspnetapp/aspnetapp.sln --no-restore

      - name: Test
        run: dotnet test ./aspnet/aspnetapp/aspnetapp.sln --no-build
      
      - name: Run Code Format Check
        run: dotnet format ./aspnet/aspnetapp/aspnetapp.sln --verify-no-changes

      - name: Run Static Code Analysis
        run: dotnet build ./aspnet/aspnetapp/aspnetapp.sln --no-restore -warnaserror

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: aspnetapp-output
          path: aspnet/aspnetapp/bin/Release/net9.0/
        
  docker-deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: aspnetapp-output

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE -f aspnet/Dockerfile aspnet/

      - name: Push Docker image
        run: docker push $DOCKER_IMAGE

      - name: SSH Deploy to Azure VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            docker pull pptloc/aspnetapp
            docker stop aspnetapp || true
            docker rm aspnetapp || true
            docker run -d --name aspnetapp -p 80:8080 pptloc/aspnetapp

